### ISSUE TITLE
Just asking

### ISSUE THREAD

**Issue by InsaneLegacy** [filfat/MineiaGo#5]
How far is this project are there inventory etc or is there a to-do list?

**Comment by filfat** [comment]
It’s pretty much in the barebones stage.
We have a Bedrock server listing for and accepting connections. We can kind of spawn a player (sometimes, depending on the clients state).

There’s a whole lot left todo and I’ll create a TODO.md and a CONTRIBUTING.md document ASAP.
But the gist of it is:
* Figure out the best way to communicate with the underlaying java server (see https://www.spigotmc.org/threads/programmatically-create-a-new-client.384098/). Creating a Minecraft client ourselves isn’t the right way to go due to several reasons (socket limits, having to send with details OTA, etc)
* implement both Java and Bedrock chunks in the style of https://github.com/PrismarineJS/prismarine-chunk.
* Figure out a better way to structure the packet handlers. I don’t like how it’s currently a massive file.
* and a whole lot more.

Feel free to contribute in whatever way you can or want to. Doesn’t matter if it’s a simple spelling fix or a huge implementation/rewrite! :)
